/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js}'],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#e040a0',
        'surface-container-low': '#fbf2fb',
        'surface-container': '#f8eef8',
        'tertiary-container': '#40c0ee',
        'secondary-container': '#eedcff',
        'on-secondary-fixed-variant': '#4a3068',
        'on-secondary-container': '#2e2040',
        'inverse-on-surface': '#fef7ff',
        'on-surface-variant': '#604868',
        'on-secondary-fixed': '#1a1030',
        secondary: '#7c52aa',
        'tertiary-fixed-dim': '#80d0f0',
        'inverse-surface': '#2e1a28',
        'surface-container-highest': '#ece2ec',
        background: '#fef7ff',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#f0a0cc',
        'on-primary-fixed-variant': '#a02070',
        'secondary-fixed-dim': '#c8a8e8',
        'on-surface': '#2e1a28',
        'on-tertiary-container': '#00334d',
        'primary-fixed-dim': '#f0a0cc',
        'surface-dim': '#e0d6e0',
        primary: '#e040a0',
        'on-background': '#2e1a28',
        'surface-container-high': '#f2e8f2',
        outline: '#907898',
        error: '#e53e3e',
        tertiary: '#0096cc',
        'on-tertiary-fixed-variant': '#005580',
        surface: '#fef7ff',
        'secondary-fixed': '#eedcff',
        'on-primary': '#ffffff',
        'on-error-container': '#9b1c1c',
        'tertiary-fixed': '#c8eaff',
        'error-container': '#ffe8e8',
        'on-primary-fixed': '#3d0028',
        'on-error': '#ffffff',
        'surface-variant': '#f2e8f2',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#001a33',
        'surface-bright': '#fef7ff',
        'on-tertiary': '#ffffff',
        'primary-container': '#f080c0',
        'on-primary-container': '#2e1a28',
        'primary-fixed': '#ffd6ee',
        'outline-variant': '#dcc8e0',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
      },
      fontFamily: {
        headline: ['"DM Sans"', 'sans-serif'],
        display: ['"DM Sans"', 'sans-serif'],
        body: ['"DM Sans"', 'sans-serif'],
        label: ['"DM Sans"', 'sans-serif'],
        sans: ['"DM Sans"', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
